### PR TITLE
Replace `pkg_resources.parse_version` with `packaging.version.Version`

### PR DESCRIPTION
**Pull request by jwodder**
`pkg_resources` is deprecated and should no longer be used.  This PR replaces the use of `pkg_resources.parse_version()` with its non-deprecated equivalent, `packaging.version.Version`.

### CODE REVIEW

**Comment by yarikoptic** [comment]
@satra ping on this PR. May be you could add me and @jwodder to "legit" contributors so at least workflows run without needing to be approved?

**Comment by jwodder** [comment]
@satra The tests are failing because codecov.io is having issues, and then the default `fail-fast` strategy for Actions matrices is causing all other running tests to be cancelled.  I recommend the following:

* Set `fail_ci_if_error: false` in the codecov step in the workflow
* (Optional) Add `fail-fast: false` under `strategy:` in the workflow

**Comment by yarikoptic** [comment]
both sound good to me @jwodder , let's proceed that way

**Review by effigies — APPROVED** [review]
Shall we merge and get this released?

**Comment by satra** [comment]
released.

**Comment by effigies** [comment]
Thanks, @satra!

**Pull request merged**
